headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

  [functions."*"]

[build]
publish = "F:\\JOB APP"
publishOrigin = "config"
commandOrigin = "config"
command = "echo netlify-static-deploy"

  [build.environment]
  NODE_VERSION = "18"

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[[headers]]
for = "/*"

  [headers.values]
  Cache-Control = "no-cache, no-store, must-revalidate"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"

[[redirects]]
from = "/admin"
to = "/admin.html"
status = 200
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]